{
  imports = [
    ./extra-packages.nix
    ./autopairs.nix
    ./snippets.nix
    ./blink-cmp.nix
    ./telescope.nix
    ./languages.nix
    ./notify.nix
    ./ui.nix
    ./keymaps.nix
    ./statusline.nix
    ./extra-plugins.nix
    ./options.nix
    ./treesitter.nix
    ./git.nix
    ./lsp.nix
    ./mini.nix
    ./utilities.nix
    ./binds.nix
  ];
}
